export type Domain = "ML" | "NLP" | "Vision" | "Bio";

export type DeadlineKind =
  | "abstract"
  | "paper"
  | "supplemental"
  | "review"
  | "response"
  | "commitment"
  | "decision"
  | "camera"
  | "conference"
  | "registration"
  | "other";

export type Confidence = "official" | "preliminary" | "tbd" | "conflict";

export type DeadlineEvent = {
  id: string;
  kind: DeadlineKind;
  label: string;
  date?: string;
  endDate?: string;
  timezone: string;
  confidence: Confidence;
  sourceUrl: string;
  track?: string;
  emphasis?: boolean;
  notes?: string;
};

export type Conference = {
  id: string;
  acronym: string;
  name: string;
  year: number;
  domain: Domain;
  location?: string;
  venue?: string;
  sourceUrl: string;
  lastChecked: string;
  notes?: string;
  events: DeadlineEvent[];
};

const checked = "2026-07-07";

export const conferences: Conference[] = [
  {
    id: "neurips-2026",
    acronym: "NeurIPS",
    name: "Conference on Neural Information Processing Systems",
    year: 2026,
    domain: "ML",
    location: "San Diego, CA, USA",
    sourceUrl: "https://neurips.cc/Conferences/2026/Dates",
    lastChecked: checked,
    events: [
      {
        id: "neurips-2026-abstract",
        kind: "abstract",
        label: "Paper abstract submission",
        date: "2026-05-04",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://neurips.cc/Conferences/2026/Dates",
        emphasis: true,
      },
      {
        id: "neurips-2026-paper",
        kind: "paper",
        label: "Full paper submission",
        date: "2026-05-06",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://neurips.cc/Conferences/2026/Dates",
        emphasis: true,
      },
      {
        id: "neurips-2026-reviews",
        kind: "review",
        label: "Reviews released",
        date: "2026-07-22",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://neurips.cc/Conferences/2026/Dates",
      },
      {
        id: "neurips-2026-discussion",
        kind: "response",
        label: "Author, reviewer, and AC discussion",
        date: "2026-07-27",
        endDate: "2026-08-03",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://neurips.cc/Conferences/2026/Dates",
      },
      {
        id: "neurips-2026-reviewer-discussion",
        kind: "response",
        label: "Reviewer and AC discussion",
        date: "2026-08-03",
        endDate: "2026-08-10",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://neurips.cc/Conferences/2026/Dates",
      },
      {
        id: "neurips-2026-notification",
        kind: "decision",
        label: "Paper author notification",
        date: "2026-09-24",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://neurips.cc/Conferences/2026/Dates",
      },
      {
        id: "neurips-2026-conference",
        kind: "conference",
        label: "Conference",
        date: "2026-12-06",
        endDate: "2026-12-12",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://neurips.cc/Conferences/2026/Dates",
      },
    ],
  },
  {
    id: "icml-2026",
    acronym: "ICML",
    name: "International Conference on Machine Learning",
    year: 2026,
    domain: "ML",
    location: "Seoul, South Korea",
    venue: "COEX Convention & Exhibition Center",
    sourceUrl: "https://icml.cc/Conferences/2026/Dates",
    lastChecked: checked,
    events: [
      {
        id: "icml-2026-open",
        kind: "other",
        label: "Submission site opens",
        date: "2026-01-08",
        timezone: "UTC",
        confidence: "official",
        sourceUrl: "https://icml.cc/Conferences/2026/CallForPapers",
      },
      {
        id: "icml-2026-abstract",
        kind: "abstract",
        label: "Abstract submission",
        date: "2026-01-23",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://icml.cc/Conferences/2026/CallForPapers",
        emphasis: true,
      },
      {
        id: "icml-2026-paper",
        kind: "paper",
        label: "Full paper submission",
        date: "2026-01-28",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://icml.cc/Conferences/2026/CallForPapers",
        emphasis: true,
      },
      {
        id: "icml-2026-reviews",
        kind: "review",
        label: "Reviews released",
        date: "2026-03-24",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://icml.cc/Conferences/2026/Dates",
      },
      {
        id: "icml-2026-response",
        kind: "response",
        label: "Author response deadline",
        date: "2026-03-30",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://icml.cc/Conferences/2026/Dates",
      },
      {
        id: "icml-2026-discussion",
        kind: "response",
        label: "Author-reviewer discussion",
        date: "2026-03-31",
        endDate: "2026-04-07",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://icml.cc/Conferences/2026/Dates",
      },
      {
        id: "icml-2026-notification",
        kind: "decision",
        label: "Author notification",
        date: "2026-04-30",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://icml.cc/Conferences/2026/Dates",
      },
      {
        id: "icml-2026-camera",
        kind: "camera",
        label: "Camera-ready",
        date: "2026-05-28",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://icml.cc/Conferences/2026/AuthorInstructions",
      },
      {
        id: "icml-2026-conference",
        kind: "conference",
        label: "Conference",
        date: "2026-07-06",
        endDate: "2026-07-11",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://icml.cc/",
      },
    ],
  },
  {
    id: "iclr-2026",
    acronym: "ICLR",
    name: "International Conference on Learning Representations",
    year: 2026,
    domain: "ML",
    location: "Rio de Janeiro, Brazil",
    venue: "Riocentro Convention and Event Center",
    sourceUrl: "https://iclr.cc/Conferences/2026/AuthorGuide",
    lastChecked: checked,
    notes:
      "ICLR 2026 submission deadlines are in September 2025 because they precede the April 2026 conference. The call-for-papers page lists final decisions as Jan 25, while the author guide review process lists Jan 22. The app keeps Jan 22 as a conflict-tagged date because it is the more detailed author-guide schedule.",
    events: [
      {
        id: "iclr-2026-abstract",
        kind: "abstract",
        label: "Abstract submission",
        date: "2025-09-19",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://iclr.cc/Conferences/2026/AuthorGuide",
        emphasis: true,
      },
      {
        id: "iclr-2026-paper",
        kind: "paper",
        label: "Full paper submission",
        date: "2025-09-24",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://iclr.cc/Conferences/2026/AuthorGuide",
        emphasis: true,
      },
      {
        id: "iclr-2026-reviews",
        kind: "review",
        label: "Reviews released",
        date: "2025-11-11",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://iclr.cc/Conferences/2026/AuthorGuide",
      },
      {
        id: "iclr-2026-discussion",
        kind: "response",
        label: "Author and reviewer discussion",
        date: "2025-11-11",
        endDate: "2025-12-03",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://iclr.cc/Conferences/2026/AuthorGuide",
      },
      {
        id: "iclr-2026-decision",
        kind: "decision",
        label: "Final decisions",
        date: "2026-01-22",
        timezone: "AoE",
        confidence: "conflict",
        sourceUrl: "https://iclr.cc/Conferences/2026/AuthorGuide",
        notes: "CFP page lists Jan 25; author guide lists Jan 22.",
      },
      {
        id: "iclr-2026-conference",
        kind: "conference",
        label: "Conference",
        date: "2026-04-23",
        endDate: "2026-04-27",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://iclr.cc/",
      },
    ],
  },
  {
    id: "iclr-2027",
    acronym: "ICLR",
    name: "International Conference on Learning Representations",
    year: 2027,
    domain: "ML",
    location: "West Coast North America",
    sourceUrl: "https://iclr.cc/Conferences/FutureMeetings",
    lastChecked: checked,
    notes:
      "The official ICLR Future Meetings page lists ICLR 2027 as West Coast North America. The official 2027 Dates and Call for Papers pages are not published yet, so abstract and paper submission deadlines are marked TBD.",
    events: [
      {
        id: "iclr-2027-abstract-tbd",
        kind: "abstract",
        label: "Abstract submission",
        timezone: "AoE",
        confidence: "tbd",
        sourceUrl: "https://iclr.cc/Conferences/FutureMeetings",
        emphasis: true,
        notes:
          "Official ICLR 2027 abstract deadline is not announced yet. The 2027 Dates and Call for Papers pages returned 404 when checked.",
      },
      {
        id: "iclr-2027-paper-tbd",
        kind: "paper",
        label: "Full paper submission",
        timezone: "AoE",
        confidence: "tbd",
        sourceUrl: "https://iclr.cc/Conferences/FutureMeetings",
        emphasis: true,
        notes:
          "Official ICLR 2027 paper deadline is not announced yet. The 2027 Dates and Call for Papers pages returned 404 when checked.",
      },
      {
        id: "iclr-2027-conference-tbd",
        kind: "conference",
        label: "Conference dates",
        timezone: "local",
        confidence: "tbd",
        sourceUrl: "https://iclr.cc/Conferences/FutureMeetings",
        notes:
          "Official future-meetings page lists the region but not exact conference dates.",
      },
    ],
  },
  {
    id: "arr-2026",
    acronym: "ARR",
    name: "ACL Rolling Review",
    year: 2026,
    domain: "NLP",
    sourceUrl: "https://aclrollingreview.org/dates",
    lastChecked: checked,
    notes:
      "ARR cycles are shared review infrastructure for ACL-family venues. Most cycles do not have a separate abstract deadline.",
    events: [
      {
        id: "arr-2026-march-paper",
        kind: "paper",
        label: "March cycle submission",
        date: "2026-03-16",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "March cycle",
        emphasis: true,
      },
      {
        id: "arr-2026-march-reviewer",
        kind: "registration",
        label: "March cycle reviewer registration",
        date: "2026-03-18",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "March cycle",
      },
      {
        id: "arr-2026-march-response",
        kind: "response",
        label: "March cycle author response",
        date: "2026-04-28",
        endDate: "2026-05-04",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "March cycle",
      },
      {
        id: "arr-2026-march-meta",
        kind: "review",
        label: "March cycle meta-reviews",
        date: "2026-05-21",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "March cycle",
      },
      {
        id: "arr-2026-may-paper",
        kind: "paper",
        label: "May cycle submission",
        date: "2026-05-25",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "May cycle",
        emphasis: true,
      },
      {
        id: "arr-2026-may-reviewer",
        kind: "registration",
        label: "May cycle reviewer registration",
        date: "2026-05-27",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "May cycle",
      },
      {
        id: "arr-2026-may-response",
        kind: "response",
        label: "May cycle author response",
        date: "2026-07-08",
        endDate: "2026-07-14",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "May cycle",
      },
      {
        id: "arr-2026-may-meta",
        kind: "review",
        label: "May cycle meta-reviews",
        date: "2026-07-30",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "May cycle",
      },
      {
        id: "arr-2026-august-paper",
        kind: "paper",
        label: "August cycle submission",
        date: "2026-08-03",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "August cycle",
        emphasis: true,
      },
      {
        id: "arr-2026-august-reviewer",
        kind: "registration",
        label: "August cycle reviewer registration",
        date: "2026-08-05",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "August cycle",
      },
      {
        id: "arr-2026-august-response",
        kind: "response",
        label: "August cycle response and discussion",
        date: "2026-09-14",
        endDate: "2026-09-24",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "August cycle",
      },
      {
        id: "arr-2026-august-meta",
        kind: "review",
        label: "August cycle meta-reviews",
        date: "2026-10-08",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "August cycle",
      },
      {
        id: "arr-2026-october-paper",
        kind: "paper",
        label: "October cycle submission",
        date: "2026-10-12",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "October cycle",
        emphasis: true,
      },
      {
        id: "arr-2026-october-end",
        kind: "review",
        label: "October cycle end",
        date: "2026-12-20",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://aclrollingreview.org/dates",
        track: "October cycle",
      },
    ],
  },
  {
    id: "acl-2026",
    acronym: "ACL",
    name: "Annual Meeting of the Association for Computational Linguistics",
    year: 2026,
    domain: "NLP",
    location: "San Diego, CA, USA",
    sourceUrl: "https://2026.aclweb.org/",
    lastChecked: checked,
    events: [
      {
        id: "acl-2026-paper",
        kind: "paper",
        label: "ARR submission deadline",
        date: "2026-01-05",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.aclweb.org/",
        emphasis: true,
        notes: "ACL 2026 uses ARR; no separate abstract deadline is listed.",
      },
      {
        id: "acl-2026-reviews",
        kind: "review",
        label: "ARR reviews and meta-reviews",
        date: "2026-03-10",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.aclweb.org/",
      },
      {
        id: "acl-2026-commitment",
        kind: "commitment",
        label: "ACL commitment deadline",
        date: "2026-03-14",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.aclweb.org/",
      },
      {
        id: "acl-2026-notification",
        kind: "decision",
        label: "Acceptance notification",
        date: "2026-04-04",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.aclweb.org/",
      },
      {
        id: "acl-2026-camera",
        kind: "camera",
        label: "Camera-ready",
        date: "2026-04-19",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.aclweb.org/",
      },
      {
        id: "acl-2026-conference",
        kind: "conference",
        label: "Conference",
        date: "2026-07-02",
        endDate: "2026-07-07",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://2026.aclweb.org/",
      },
    ],
  },
  {
    id: "emnlp-2026",
    acronym: "EMNLP",
    name: "Empirical Methods in Natural Language Processing",
    year: 2026,
    domain: "NLP",
    sourceUrl: "https://2026.emnlp.org/calls/main_conference_papers/",
    lastChecked: checked,
    events: [
      {
        id: "emnlp-2026-paper",
        kind: "paper",
        label: "ARR submission deadline",
        date: "2026-05-25",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.emnlp.org/calls/main_conference_papers/",
        emphasis: true,
        notes: "EMNLP 2026 uses ARR; no separate abstract deadline is listed.",
      },
      {
        id: "emnlp-2026-reviewer",
        kind: "registration",
        label: "Reviewer registration for all authors",
        date: "2026-05-27",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.emnlp.org/calls/main_conference_papers/",
      },
      {
        id: "emnlp-2026-response",
        kind: "response",
        label: "Author response and discussion",
        date: "2026-07-07",
        endDate: "2026-07-13",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.emnlp.org/calls/main_conference_papers/",
      },
      {
        id: "emnlp-2026-meta",
        kind: "review",
        label: "Meta-review released",
        date: "2026-07-30",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.emnlp.org/calls/main_conference_papers/",
      },
      {
        id: "emnlp-2026-commitment",
        kind: "commitment",
        label: "EMNLP commitment deadline",
        date: "2026-08-02",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.emnlp.org/calls/main_conference_papers/",
      },
      {
        id: "emnlp-2026-notification",
        kind: "decision",
        label: "Acceptance notification",
        date: "2026-08-20",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.emnlp.org/calls/main_conference_papers/",
      },
      {
        id: "emnlp-2026-camera",
        kind: "camera",
        label: "Camera-ready",
        date: "2026-08-30",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://2026.emnlp.org/calls/main_conference_papers/",
      },
      {
        id: "emnlp-2026-conference",
        kind: "conference",
        label: "Main conference",
        date: "2026-10-24",
        endDate: "2026-10-29",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://2026.emnlp.org/calls/main_conference_papers/",
      },
    ],
  },
  {
    id: "colm-2026",
    acronym: "COLM",
    name: "Conference on Language Modeling",
    year: 2026,
    domain: "NLP",
    location: "San Francisco, CA, USA",
    venue: "Hilton Union Square",
    sourceUrl: "https://colmweb.org/dates.html",
    lastChecked: checked,
    events: [
      {
        id: "colm-2026-abstract",
        kind: "abstract",
        label: "Abstract deadline",
        date: "2026-03-26",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://colmweb.org/dates.html",
        emphasis: true,
      },
      {
        id: "colm-2026-paper",
        kind: "paper",
        label: "Full paper submission",
        date: "2026-03-31",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://colmweb.org/dates.html",
        emphasis: true,
      },
      {
        id: "colm-2026-rebuttal",
        kind: "response",
        label: "Rebuttal period",
        date: "2026-05-22",
        endDate: "2026-06-08",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://colmweb.org/dates.html",
      },
      {
        id: "colm-2026-decision",
        kind: "decision",
        label: "Decision notification",
        date: "2026-07-08",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://colmweb.org/dates.html",
      },
      {
        id: "colm-2026-conference",
        kind: "conference",
        label: "Conference",
        date: "2026-10-06",
        endDate: "2026-10-09",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://colmweb.org/",
      },
    ],
  },
  {
    id: "coling-2027",
    acronym: "COLING",
    name: "International Conference on Computational Linguistics",
    year: 2027,
    domain: "NLP",
    location: "Macau, China",
    sourceUrl: "https://2027.coling-iccl.org/",
    lastChecked: checked,
    notes:
      "The official COLING 2027 site lists important dates as TBD. A preliminary CFP on the ELRA corpora list says COLING will adopt ARR and points to the October 2026 ARR cycle.",
    events: [
      {
        id: "coling-2027-paper-prelim",
        kind: "paper",
        label: "ARR submission deadline",
        date: "2026-10-12",
        timezone: "AoE",
        confidence: "preliminary",
        sourceUrl:
          "https://list.elra.info/mailman3/hyperkitty/list/corpora%40list.elra.info/thread/HIP4GRRVBBVGXCRXJDBSYPWQJTVGNXS6/",
        emphasis: true,
        notes: "Preliminary CFP; official site still says TBD.",
      },
      {
        id: "coling-2027-important-dates-tbd",
        kind: "other",
        label: "Official submission dates",
        timezone: "AoE",
        confidence: "tbd",
        sourceUrl: "https://2027.coling-iccl.org/",
        notes: "Official website currently lists important dates as TBD.",
      },
      {
        id: "coling-2027-conference",
        kind: "conference",
        label: "Conference",
        date: "2027-05-09",
        endDate: "2027-05-14",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://2027.coling-iccl.org/",
      },
    ],
  },
  {
    id: "cvpr-2026",
    acronym: "CVPR",
    name: "Computer Vision and Pattern Recognition",
    year: 2026,
    domain: "Vision",
    location: "Denver, CO, USA",
    sourceUrl: "https://cvpr.thecvf.com/Conferences/2026/CallForPapers",
    lastChecked: checked,
    events: [
      {
        id: "cvpr-2026-abstract",
        kind: "abstract",
        label: "Abstract submission",
        date: "2025-11-07",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://cvpr.thecvf.com/Conferences/2026/CallForPapers",
        emphasis: true,
      },
      {
        id: "cvpr-2026-paper",
        kind: "paper",
        label: "Paper submission",
        date: "2025-11-13",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://cvpr.thecvf.com/Conferences/2026/CallForPapers",
        emphasis: true,
      },
      {
        id: "cvpr-2026-supplemental",
        kind: "supplemental",
        label: "Supplementary materials",
        date: "2025-11-20",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://cvpr.thecvf.com/Conferences/2026/CallForPapers",
      },
      {
        id: "cvpr-2026-reviews",
        kind: "review",
        label: "Reviews released",
        date: "2026-01-22",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://cvpr.thecvf.com/Conferences/2026/CallForPapers",
      },
      {
        id: "cvpr-2026-rebuttal",
        kind: "response",
        label: "Rebuttal period",
        date: "2026-01-22",
        endDate: "2026-01-29",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://cvpr.thecvf.com/Conferences/2026/CallForPapers",
      },
      {
        id: "cvpr-2026-decision",
        kind: "decision",
        label: "Final decisions",
        date: "2026-02-20",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://cvpr.thecvf.com/Conferences/2026/CallForPapers",
      },
      {
        id: "cvpr-2026-conference",
        kind: "conference",
        label: "Conference",
        date: "2026-06-03",
        endDate: "2026-06-07",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://cvpr.thecvf.com/",
      },
    ],
  },
  {
    id: "iccv-2027",
    acronym: "ICCV",
    name: "International Conference on Computer Vision",
    year: 2027,
    domain: "Vision",
    location: "Hong Kong",
    sourceUrl: "https://www.thecvf.com/?p=137",
    lastChecked: checked,
    notes:
      "Official CVF page confirms the 2027 conference dates and location. Submission dates have not been posted on the ICCV site yet.",
    events: [
      {
        id: "iccv-2027-submission-tbd",
        kind: "paper",
        label: "Submission dates",
        timezone: "TBD",
        confidence: "tbd",
        sourceUrl: "https://iccv.thecvf.com/",
        emphasis: true,
        notes: "Official submission dates are not yet announced.",
      },
      {
        id: "iccv-2027-conference",
        kind: "conference",
        label: "Conference",
        date: "2027-10-02",
        endDate: "2027-10-08",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://www.thecvf.com/?p=137",
      },
    ],
  },
  {
    id: "eccv-2026",
    acronym: "ECCV",
    name: "European Conference on Computer Vision",
    year: 2026,
    domain: "Vision",
    location: "Malmo, Sweden",
    sourceUrl: "https://eccv.ecva.net/Conferences/2026/Dates",
    lastChecked: checked,
    events: [
      {
        id: "eccv-2026-registration",
        kind: "abstract",
        label: "Paper registration",
        date: "2026-02-26",
        timezone: "22:00 UTC",
        confidence: "official",
        sourceUrl: "https://eccv.ecva.net/Conferences/2026/Dates",
        emphasis: true,
      },
      {
        id: "eccv-2026-paper",
        kind: "paper",
        label: "Main conference submission",
        date: "2026-03-05",
        timezone: "22:00 UTC",
        confidence: "official",
        sourceUrl: "https://eccv.ecva.net/Conferences/2026/Dates",
        emphasis: true,
      },
      {
        id: "eccv-2026-supplemental",
        kind: "supplemental",
        label: "Supplemental materials",
        date: "2026-03-12",
        timezone: "22:00 UTC",
        confidence: "official",
        sourceUrl: "https://eccv.ecva.net/Conferences/2026/Dates",
      },
      {
        id: "eccv-2026-reviews",
        kind: "review",
        label: "Reviews released",
        date: "2026-05-02",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://eccv.ecva.net/Conferences/2026/Dates",
      },
      {
        id: "eccv-2026-rebuttal",
        kind: "response",
        label: "Rebuttal deadline",
        date: "2026-05-11",
        timezone: "21:00 UTC",
        confidence: "official",
        sourceUrl: "https://eccv.ecva.net/Conferences/2026/Dates",
      },
      {
        id: "eccv-2026-decision",
        kind: "decision",
        label: "Final decisions",
        date: "2026-06-17",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://eccv.ecva.net/Conferences/2026/Dates",
      },
      {
        id: "eccv-2026-camera",
        kind: "camera",
        label: "Camera-ready",
        date: "2026-06-30",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://eccv.ecva.net/Conferences/2026/Dates",
      },
      {
        id: "eccv-2026-conference",
        kind: "conference",
        label: "Conference",
        date: "2026-09-08",
        endDate: "2026-09-13",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://eccv.ecva.net/",
      },
    ],
  },
  {
    id: "recomb-2026",
    acronym: "RECOMB",
    name: "Research in Computational Molecular Biology",
    year: 2026,
    domain: "Bio",
    location: "Thessaloniki, Greece",
    sourceUrl: "https://recomb.org/recomb2026/keydates_and_deadlines.html",
    lastChecked: checked,
    notes:
      "The official key-dates page lists Nov 20 for full paper updates. Some social posts showed Nov 14; this app follows the official key-dates page.",
    events: [
      {
        id: "recomb-2026-abstract",
        kind: "abstract",
        label: "Abstract submission",
        date: "2025-11-07",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://recomb.org/recomb2026/keydates_and_deadlines.html",
        emphasis: true,
      },
      {
        id: "recomb-2026-paper",
        kind: "paper",
        label: "Full paper submission",
        date: "2025-11-20",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://recomb.org/recomb2026/keydates_and_deadlines.html",
        emphasis: true,
      },
      {
        id: "recomb-2026-notification",
        kind: "decision",
        label: "Author notification",
        date: "2026-01-16",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://recomb.org/recomb2026/keydates_and_deadlines.html",
      },
      {
        id: "recomb-2026-final",
        kind: "camera",
        label: "Final versions due",
        date: "2026-02-25",
        timezone: "AoE",
        confidence: "official",
        sourceUrl: "https://recomb.org/recomb2026/keydates_and_deadlines.html",
      },
      {
        id: "recomb-2026-conference",
        kind: "conference",
        label: "Conference",
        date: "2026-05-26",
        endDate: "2026-05-29",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://recomb.org/recomb2026/",
      },
    ],
  },
  {
    id: "ismb-2026",
    acronym: "ISMB",
    name: "Intelligent Systems for Molecular Biology",
    year: 2026,
    domain: "Bio",
    location: "Washington, DC, USA",
    sourceUrl: "https://www.iscb.org/ismb2026/home",
    lastChecked: checked,
    notes:
      "ISMB has separate proceedings-paper and abstract-presentation deadlines. ISMIR was intentionally excluded.",
    events: [
      {
        id: "ismb-2026-proceedings",
        kind: "paper",
        label: "Proceedings paper submission",
        date: "2026-01-20",
        timezone: "AoE",
        confidence: "official",
        sourceUrl:
          "https://www.iscb.org/ismb2026/call-for-submissions/proceedings",
        emphasis: true,
      },
      {
        id: "ismb-2026-abstract",
        kind: "abstract",
        label: "Talk/poster abstract submission",
        date: "2026-04-09",
        timezone: "Any Time Zone",
        confidence: "official",
        sourceUrl:
          "https://www.iscb.org/ismb2026/call-for-submissions/abstracts",
        emphasis: true,
      },
      {
        id: "ismb-2026-fee",
        kind: "registration",
        label: "Proceedings publication fee",
        date: "2026-05-07",
        timezone: "local",
        confidence: "official",
        sourceUrl:
          "https://www.iscb.org/ismb2026/call-for-submissions/proceedings",
      },
      {
        id: "ismb-2026-conference",
        kind: "conference",
        label: "Conference",
        date: "2026-07-12",
        endDate: "2026-07-16",
        timezone: "local",
        confidence: "official",
        sourceUrl: "https://www.iscb.org/ismb2026/home",
      },
    ],
  },
];
